apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bonfire
  labels:
    build.appstudio.redhat.com/pipeline: "bonfire"
spec:
  params:
    - name: SNAPSHOT
      type: string
      description: |
        Spec section of an ApplicationSnapshot resource. Not all fields of the
        resource are required. A minimal example:
          {
            "components": [
              {
                "containerImage": "quay.io/example/repo:latest"
              }
            ]
          }
        Each "containerImage" in the "components" array is validated.
  results:
    - name: TEST_OUTPUT
      value: "$(tasks.run-test.results.TEST_OUTPUT)"
      description: ""
  finally:
    - name: teardown
      params:
        - name: NS
          value: "$(tasks.reserve-namespace.results.NS)"
        - name: NS_REQUESTER
          value: "rhtap-$(context.pipelineRun.name)"
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/gbenhaim/cicd-tools.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tekton/tasks/teardown.yaml        
  tasks:
    - name: reserve-namespace
      params:
        - name: NS_REQUESTER
          value: "rhtap-$(context.pipelineRun.name)"
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/gbenhaim/cicd-tools.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tekton/tasks/reserve-namespace.yaml
    - name: deploy-application
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
        - name: NS
          value: "$(tasks.reserve-namespace.results.NS)"
        - name: NS_REQUESTER
          value: "rhtap-$(context.pipelineRun.name)"
      runAfter:
        - reserve-namespace
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/gbenhaim/cicd-tools.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tekton/tasks/deploy.yaml
    - name: run-test
      params:
        - name: NS
          value: "$(tasks.reserve-namespace.results.NS)"
        - name: NS_REQUESTER
          value: "rhtap-$(context.pipelineRun.name)"
      runAfter:
        - deploy-application
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/gbenhaim/cicd-tools.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tekton/tasks/run-test.yaml

