name: Run tests
run-name: Run tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false
          submodules: true
      - name: BATS tests
        run: ./test/bats/bin/bats test
      - name: E2E tests
        run: |
          for test_script in test/e2e/test_e2e_load_library*; do
            echo "Running $test_script"
            bash -x $test_script || exit 1
          done
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
        with:
          check_together: 'yes'
          scandir: './src'

  # https://github.com/bats-core/bats-core/blob/855844b8344e67d60dc0f43fa39817ed7787f141/.github/workflows/tests.yml#L326
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false
          submodules: recursive
      - run: ./test/generate_coverage.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: code-coverage-report
          path: coverage/*
      - name: Print the Total Coverage
        id: coverage-percent
        shell: bash
        env:
          minimum_coverage: 90.01
        run: test/check_coverage.sh
